//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Engine.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adventurer pass.
        /// </summary>
        public static string resAdventurerPass {
            get {
                return ResourceManager.GetString("resAdventurerPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adventurer passes.
        /// </summary>
        public static string resAdventurerPassPlural {
            get {
                return ResourceManager.GetString("resAdventurerPassPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear the Alchemist garden.
        /// </summary>
        public static string resAlchemistGarden {
            get {
                return ResourceManager.GetString("resAlchemistGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kill rats in the alchemist&apos;s garden and bring back 3 rat tails. You will receive a healing potion and 10 gold pieces..
        /// </summary>
        public static string resAlchemistGardenInfo {
            get {
                return ResourceManager.GetString("resAlchemistGardenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Club.
        /// </summary>
        public static string resClub {
            get {
                return ResourceManager.GetString("resClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clubs.
        /// </summary>
        public static string resClubPlural {
            get {
                return ResourceManager.GetString("resClubPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear the farmer&apos;s field.
        /// </summary>
        public static string resFarmerField {
            get {
                return ResourceManager.GetString("resFarmerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kill snakes in the farmer&apos;s field and bring back 3 snake fangs. You will receive an adventurer&apos;s pass and 20 gold pieces..
        /// </summary>
        public static string resFarmerFieldInfo {
            get {
                return ResourceManager.GetString("resFarmerFieldInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Giant spider.
        /// </summary>
        public static string resGiantSpider {
            get {
                return ResourceManager.GetString("resGiantSpider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Healing potion.
        /// </summary>
        public static string resHealingPotion {
            get {
                return ResourceManager.GetString("resHealingPotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Healing potions.
        /// </summary>
        public static string resHealingPotionPlural {
            get {
                return ResourceManager.GetString("resHealingPotionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Piece of fur.
        /// </summary>
        public static string resPieceFur {
            get {
                return ResourceManager.GetString("resPieceFur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pieces of fur.
        /// </summary>
        public static string resPieceFurPlural {
            get {
                return ResourceManager.GetString("resPieceFurPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rat.
        /// </summary>
        public static string resRat {
            get {
                return ResourceManager.GetString("resRat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rat tail.
        /// </summary>
        public static string resRatTail {
            get {
                return ResourceManager.GetString("resRatTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rat tails.
        /// </summary>
        public static string resRatTailPlural {
            get {
                return ResourceManager.GetString("resRatTailPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rusty sword.
        /// </summary>
        public static string resRustySword {
            get {
                return ResourceManager.GetString("resRustySword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rusty swords.
        /// </summary>
        public static string resRustySwordPlural {
            get {
                return ResourceManager.GetString("resRustySwordPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snake.
        /// </summary>
        public static string resSnake {
            get {
                return ResourceManager.GetString("resSnake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SnakeFang.
        /// </summary>
        public static string resSnakeFang {
            get {
                return ResourceManager.GetString("resSnakeFang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snake Fangs.
        /// </summary>
        public static string resSnakeFangPlural {
            get {
                return ResourceManager.GetString("resSnakeFangPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snakeskin.
        /// </summary>
        public static string resSnakeSkin {
            get {
                return ResourceManager.GetString("resSnakeSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snakeskins.
        /// </summary>
        public static string resSnakeSkinPlural {
            get {
                return ResourceManager.GetString("resSnakeSkinPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spider fang.
        /// </summary>
        public static string resSpiderFang {
            get {
                return ResourceManager.GetString("resSpiderFang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spider fangs.
        /// </summary>
        public static string resSpiderFangPlural {
            get {
                return ResourceManager.GetString("resSpiderFangPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spider silk.
        /// </summary>
        public static string resSpiderSilk {
            get {
                return ResourceManager.GetString("resSpiderSilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spider silks.
        /// </summary>
        public static string resSpiderSilkPlural {
            get {
                return ResourceManager.GetString("resSpiderSilkPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alchemist&apos;s garden.
        /// </summary>
        public static string strAlchemistGarden {
            get {
                return ResourceManager.GetString("strAlchemistGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Many plants are growing here..
        /// </summary>
        public static string strAlchemistGardenDesc {
            get {
                return ResourceManager.GetString("strAlchemistGardenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alchemist&apos;s hut.
        /// </summary>
        public static string strAlchemistHut {
            get {
                return ResourceManager.GetString("strAlchemistHut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are many strange plants on the shelves..
        /// </summary>
        public static string strAlchemistHutDesc {
            get {
                return ResourceManager.GetString("strAlchemistHutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bridge.
        /// </summary>
        public static string strBridge {
            get {
                return ResourceManager.GetString("strBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A stone bridge crosses a wide river..
        /// </summary>
        public static string strBridgeDesc {
            get {
                return ResourceManager.GetString("strBridgeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Farmer&apos;s field.
        /// </summary>
        public static string strFarmerField {
            get {
                return ResourceManager.GetString("strFarmerField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You see rows of vegetables growing here..
        /// </summary>
        public static string strFarmerFieldDesc {
            get {
                return ResourceManager.GetString("strFarmerFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Farmhouse.
        /// </summary>
        public static string strFarmhouse {
            get {
                return ResourceManager.GetString("strFarmhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is a small farmhouse, with a farmer in front..
        /// </summary>
        public static string strFarmhouseDesc {
            get {
                return ResourceManager.GetString("strFarmhouseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forest.
        /// </summary>
        public static string strForest {
            get {
                return ResourceManager.GetString("strForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You see spider webs covering covering the trees in this forest..
        /// </summary>
        public static string strForestDesc {
            get {
                return ResourceManager.GetString("strForestDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guard post.
        /// </summary>
        public static string strGuardPost {
            get {
                return ResourceManager.GetString("strGuardPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is a large, tough-looking guard here..
        /// </summary>
        public static string strGuardPostDesc {
            get {
                return ResourceManager.GetString("strGuardPostDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string strHome {
            get {
                return ResourceManager.GetString("strHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is your home....
        /// </summary>
        public static string strHomeDesc {
            get {
                return ResourceManager.GetString("strHomeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Town Square.
        /// </summary>
        public static string strTownSquare {
            get {
                return ResourceManager.GetString("strTownSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You see a fountain....
        /// </summary>
        public static string strTownSquareDesc {
            get {
                return ResourceManager.GetString("strTownSquareDesc", resourceCulture);
            }
        }
    }
}
